# Generated by Django 4.2.1 on 2023-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('miejsce', models.CharField(max_length=100)),
                ('wymagania', models.CharField(max_length=100)),
                ('stanowisko', models.CharField(max_length=100)),
                ('wynagrodzenie', models.CharField(max_length=100)),
                ('test', models.BooleanField(default=False)),
            ],
        ),
    ]
